### PR TITLE
All models implemented (fixes #8-11)

### LINKED ISSUE #8: Implement Node model
self explanatory

### PR DESCRIPTION
**Pull request by LukasSlouka**

### CODE REVIEW

**Comment by cibo94** [comment]
Hell no, you should not merge this

**Comment by cibo94** [comment]
__str__ should return XML formated string

**Comment by LukasSlouka** [comment]
absolutely not

**Comment by LukasSlouka** [comment]
there will be separate function for it. XML wont be created by print method...

**Comment by cibo94** [comment]
lets go to the IRC and there we will discuss this

**Pull request merged**
